#                             Caeser-Fibonacci Guess Game

## Needed libraries

In [15]:
import random
import time
import matplotlib.pyplot as plt
import numpy as np

In [3]:
fibonacci =[1,1]
for i in range(0,16):
    fibonacci.append(fibonacci[i]+fibonacci[i+1])
print(fibonacci)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584]


## Words and Hints lists

In [4]:
words=["tea",]
hints=["some thing you drink in the morning",]

## secret word

In [5]:
secret_index=random.randrange(0,len(words))
secret_word=words[secret_index]
secret_hint=hints[secret_index]
print(secret_word,":" ,secret_hint)

tea : some thing you drink in the morning


## shifting direction and value lists

In [6]:
shift_directions=["➡️" ,"⬅️"]
shift_values=[row+col ,fibonacci[row] , col**2 , 8+5*9/3 , 40 ,
              row+col ,fibonacci[row] , col**2 , 8+5*9/3 , 40 ,
              row+col ,fibonacci[row] , col**2 , 8+5*9/3 , 40 , 74
              ]
shift_values_str=['row+col' ,'fibonacci[row]' , 'col**2' , '8+5*9/3' , '40' ,
              'row+col' ,'fibonacci[row]' , 'col**2' , '8+5*9/3' , '40' ,
              'row+col' ,'fibonacci[row]' , 'col**2' , '8+5*9/3' , '40' , '74'
              ]

## Encryption of the secret word

In [7]:
alphabet= list('abcdefghijklmnopqrstuvwxyz')

def Encryption(word , dirc , val):
    word=list(word)
    for i in range(len(word)):
        if dirc[i]=="➡️":
            new_letter_index=(alphabet.index(word[i]) + val[i]) % 26    
            word[i] = alphabet[int(new_letter_index)]
        else:
            new_letter_index=(alphabet.index(word[i]) - val[i]) % 26   
            word[i] = alphabet[int(new_letter_index)]
        
    return "".join(word)

## Let's see how many points you will collect in 5 minutes ! 💪 👾

In [8]:
print("Let's see how many points you will collect in 5 minutes ! 💪 👾 ")

Let's see how many points you will collect in 5 minutes ! 💪 👾 


## Starting a turn !

In [59]:
timeout = 30  # [seconds]
timeout_start = time.time()
score=0

while time.time() < timeout_start + timeout:
    # Generate random row an column number
    row , col = (random.randint(1,9) , random.randint(1,9))
    print(row , col)

    #Selecting turn directions and values 
    turn_directions=[]
    turn_values=[]
    turn_str_vals=[]
    random_val_indices=[random.randrange(0, len(shift_values), 1) for i in range(len(secret_word))]
    arr= np.zeros((9,9))
    arr[row-1,col-1]=8
    

    for i in range(len(secret_word)):
        turn_directions.append(random.choice(shift_directions))
        turn_values.append(shift_values[random_val_indices[i]])
        turn_str_vals.append(shift_values_str[random_val_indices[i]])
    
    print(arr," ",secret_hint,"\n")
    print(turn_directions,"\n")
    print(turn_str_vals)

    encrypted_word=Encryption(secret_word,turn_directions,turn_values)
    print("",encrypted_word)

    #Starting guessing the encrypted_secret_word
    stars = "*" * len(encrypted_word)
    listOfstars= list(stars)
    listOfEncydWord=list(encrypted_word)
    is_won=False
    while time.time() < timeout_start + timeout:
        if is_won :
            break
        
        ans=input("Guess a letter  " + stars + ">")
       
        if time.time() < timeout_start + timeout:
            if ans in listOfEncydWord:
                score+=5
                indices_of_ans=[i for i , x in enumerate(listOfEncydWord) if x==ans]
                for i in range(len(indices_of_ans)):
                    listOfstars[indices_of_ans[i]] = ans
                    stars= "".join(listOfstars)
                    if "*" not in stars: 
                        print("YOU WON!")
                        print("💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥")
                        is_won=True
                    else:
                        print("Great , you can do it!")
            else:
                 print("Try another letter")
        else:
            print("Time out")
            
            
            
print("YOUR SCORE IS : ", score)

#Saving scores for ranking

# open file
with open('scores.txt', 'a') as f:

	# write elements of list
	f.write(str('%s \n' % score))

# close the file
f.close()

a_file = open("scores.txt", "r")

scores =list(set([int(line.strip()) for line in a_file]))

a_file.close()

print(scores)


#Ranking
for i in range(5):
    player=""
    r= max(scores)
    scores.remove(r)
    if score==r:
        player="Wow!That it is you ! 👏"
    print("Rank",i+1 ,":", r,player)
    

9 3
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]]   some thing you drink in the morning 

['➡️', '⬅️', '⬅️'] 

['40', 'fibonacci[row]', '8+5*9/3']
 hrd
Guess a letter  ***>h
Great , you can do it!
Guess a letter  h**>r
Great , you can do it!
Guess a letter  hr*>d
YOU WON!
💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥
9 4
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0.]]   some thing you drink in the morning 

['⬅️', '➡️', '➡️'] 

['40', 'col**2', '8+5*9/3']
 fhx
Guess a letter  ***>
Try another letter
Guess a letter  ***>
Try another letter
Guess a letter  ***>
Try another let