#                              Guess & Encrypt Game

# Game Rules 👉

# 1️⃣ I'll give you a riddle.
### e.g."some thing you drink in the morning of 3 letters" 

# 2️⃣ You guess the right word in your head.
### e.g. "tea"

# 3️⃣Then you shift each letter by directions and values below.
### e.g.  t                e                 a  

###       ['⬅️',      '⬅️',       '➡️']  =  👉  ['forward',  'backword', 'forward']

###       ['col**2',  '8+5*9/3', 'fibonacci[row]']     =  👉  ['36',  '23', '1']

###        t became j ✔️   e became h ✔️  a became b✔️
         
#                                                    *   NOTES   *
## ⚠️ fibonacci = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584,...]
### each number is the sum of the two previous numbers.

## ⚠️Value of row & col is the index of the non-zero number in the given array.
### here row = 1 & col = 6 

 [  [0. 0. 0. 0. 0. 8. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                           
    [0. 0. 0. 0. 0. 0. 0. 0. 0.]                                                                                          ]



# 4️⃣ Type the letters of the encypted gussed word one by one.

### e.g. 
###         b
###         h
###         j

# 5️⃣ Do this over 5 minutes,collect as many points as you can and try break the record of other players!


#                                     LET'S HAVE FUN 🤸‍♀️

         



## Needed libraries

In [90]:
import random
import time
import numpy as np

## Generate Fibonacci Sequence

In [91]:
fibonacci =[0,1,1]
for i in range(1,17):
    fibonacci.append(fibonacci[i]+fibonacci[i+1])
print(fibonacci)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584]


## Words and Hints lists

In [92]:
words=["tea",'coin', 'F', 'clock', 'egg', 'towel', 'echo',  'barber', 'hole', 'window', 'staircase', 'david','fire',
       'piano', 'dice', 'mirror', 'charcoal', 'shirt', 'water',
       
      
      ]
riddles=["some thing you drink in the morning",
       "I have a tail and a head but no body. What am I?",
"What’s the capital of France?",
"What has hands and a face but can’t hold anything or smile?",
"What has to be broken before you can use it?",
"What gets wet while drying?",
"What can’t talk but will reply when spoken to?",
"I shave every day but my beard stays the same. What am I?",
"What gets bigger when more is taken away?",
"What invention lets you look right through a wall?",
"What goes up and down but doesn’t move?",
"David's father has three sons: Snap, Crackle, and ___?",
"I am not alive but I grow; I don't have lungs but I need air; I don't have a mouth but water kills me. What am I?",
"What has many keys but can't even open a single door?",
"What has six faces but does not wear makeup has twenty-one eyes but cannot see?",
"I make two people out of one. What am I?",
"What is black when you buy it, red when you use it, and gray when you throw it away?",
"What has a neck but no head two arms but no hands?",
"Always in you Sometimes on you;If I surround you, I can kill you.What am I?"]
print(len(words) ,len(riddles))

19 19


## Encryption of the secret word

In [93]:
alphabet= list('abcdefghijklmnopqrstuvwxyz')

def Encryption(word , dirc , val):
    word=list(word)
    for i in range(len(word)):
        if dirc[i]=="➡️":
            new_letter_index=(alphabet.index(word[i]) + val[i]) % 26    
            word[i] = alphabet[int(new_letter_index)]
        else:
            new_letter_index=(alphabet.index(word[i]) - val[i]) % 26   
            word[i] = alphabet[int(new_letter_index)]
        
    return "".join(word)

## Let's see how many points you will collect in 5 minutes ! 💪 👾

## Starting a turn !

In [ ]:
timeout =5*60  # [seconds]
timeout_start = time.time()
score=0

while time.time() < timeout_start + timeout:
    #Secret word selecting
    secret_indices=[i for i in range(len(words))]
    secret_index=random.choice(secret_indices)
    secret_indices.remove(secret_index)
    secret_word=words[secret_index]
    secret_riddle=riddles[secret_index]
    print("Riddle : ",secret_riddle , "(of " + str(len(secret_word)) +" letters)" ,"\n") 
    
    # Generate random row an column number
    row , col = (random.randint(1,9) , random.randint(1,9))
    # shifting direction and value lists
    shift_directions=["➡️" ,"⬅️"]
    shift_values=[row+col ,fibonacci[row] , col**2 , 8+5*(9/3) , 40 ,
              row+(col*5) ,fibonacci[col] , row , col+col , 1 ,           
              ]
    shift_values_str=['row+col' ,'fibonacci[row]' , 'col**2' , '8+5*(9/3)' , '40' ,
              'row+(col*5)' ,'fibonacci[col]' , 'row' , 'col+col' , 'exp(0)' ,           
              ]

    #Selecting turn directions and values 
    turn_directions=[]
    turn_values=[]
    turn_str_vals=[]
    random_val_indices=[random.randrange(0, len(shift_values), 1) for i in range(len(secret_word))]
    arr= np.zeros((9,9))
    arr[row-1,col-1]=8
    for i in range(len(secret_word)):
        turn_directions.append(random.choice(shift_directions))
        turn_values.append(shift_values[random_val_indices[i]])
        turn_str_vals.append(shift_values_str[random_val_indices[i]])
    
    print("Directions : ",turn_directions,"\n")
    print("Values : ",turn_str_vals,"\n")
    print("The Array :","\n", arr)

    encrypted_word=Encryption(secret_word,turn_directions,turn_values)
   

    #Starting guessing the encrypted_secret_word
    stars = "*" * len(encrypted_word)
    listOfstars= list(stars)
    listOfEncydWord=list(encrypted_word)
    is_won=False
    while time.time() < timeout_start + timeout:
        if is_won :
            break
        
        ans=(input("Guess a letter  " + stars + ">")).lower()
       
        if time.time() < timeout_start + timeout:
            if (ans in alphabet):
                if ans not in stars :
                    if ans in listOfEncydWord:
                        score+=5
                        indices_of_ans=[i for i , x in enumerate(listOfEncydWord) if x==ans]
                        for i in range(len(indices_of_ans)):
                            listOfstars[indices_of_ans[i]] = ans
                            stars= "".join(listOfstars)
                        if "*" not in stars: 
                            print("YOU WON!")
                            print("💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥")
                            is_won=True
                        else:
                            print("Great , you can do it!")
                    else:
                         print("Try another letter")
                    
                else:
                    print("Bad Memory")
                    
            else:
                print("Enter a letter!")
        else:
            print("Time out")
            
            
print("YOUR SCORE IS:", score)

#Saving scores for ranking

with open('scores.txt', 'a') as f:
    f.write(str('%s \n' % score))
f.close()

a_file = open("scores.txt", "r")

scores =list(set([int(line.strip()) for line in a_file]))

a_file.close()

top_five=[]
#Ranking
for i in range(5):
    player=""
    r= max(scores)
    scores.remove(r)
    top_five.append(r)
    if score==r:
        player="Wow!That it is you ! 👏"
    print("Rank",i+1 ,":", r,player)
 
if score not in top_five :
    print("You are out of the top five  , give another try to level up!")

Riddle :  Always in you Sometimes on you;If I surround you, I can kill you.What am I? (of 5 letters) 

Directions :  ['⬅️', '➡️', '➡️', '⬅️', '➡️'] 

Values :  ['row+(col*5)', 'row+col', 'col+col', 'row+(col*5)', 'col**2'] 

The Array : 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
